Repository deepin-community/Repository-Manager, pull requests merged in 2023-07, with the labels that each got.

#34 Update repos.yml
  repos.yml
Labels: approved, lgtm, approve

#41 update repos.yml
  repos.yml
Labels: lgtm, approve

#40 update repos
  repos.yml
Labels: lgtm, approve

#49 add rust-aho-corasick
  repos.yml
Labels: lgtm

#47 update repos.yml
  repos.yml
Labels: approved

#46 update repos.yml
  repos.yml
Labels: approved

#55 Update repos.yml
  repos.yml
Labels: lgtm

#51 Update repos.yml
  repos.yml
Labels: lgtm

#57 update repo.yml
  repos.yml
Labels: lgtm

#54 add rust-rustc-hash
  repos.yml
Labels: lgtm

#58 Add parole
  repos.yml
Labels: lgtm

#65 add rust-version-check,rust-glob,rust-lazy-static
  repos.yml
Labels: lgtm

#59 add rust-unicode-width
  repos.yml
Labels: approved

#66 add rust-ansi-term
  repos.yml
Labels: lgtm

#68 feat: add fonts-intel-one-mono
  repos.yml
Labels: lgtm

#67 feat: add discus
  repos.yml
Labels: lgtm

#64 feat: add rust-either
  repos.yml
Labels: lgtm

#71 feat: add rust-winapi-i686-pc-windows-gnu
  repos.yml
Labels: lgtm

#69 feat: add rust-minimal-lexical
  repos.yml
Labels: lgtm

#72 feat: add rust-log
  repos.yml
Labels: lgtm

#75 feat: add rust-lazycell
  repos.yml
Labels: lgtm

#76 feat: add rust-cloudabi
  repos.yml
Labels: approved

#77 feat: add rust-winapi-x86-64-pc-windows-gnu
  repos.yml
Labels: lgtm

#78 feat: add rust-clap, rust-clap-lex, rust-termcolor, rust-os-str-bytes
  repos.yml
Labels: lgtm

#74 feat: add rust-cexpr, rust-lexical-core
  repos.yml
Labels: lgtm

#79 feat: add bpython, butt
  repos.yml
Labels: lgtm

#82 feat: add rust-clang-sys
  repos.yml
Labels: lgtm

#81 feat: add fonts-google-noto-sans-simplified-chinese,iotop,exim4
  repos.yml
Labels: lgtm

#80 feat: add synaptic
  repos.yml
Labels: lgtm

#85 Add wofi
  repos.yml
Labels: approved, lgtm

#63 feat: add firacode
  repos.yml
Labels: lgtm

#86 feat: add fail2ban, xfburn, tix, iftop, ristretto
  repos.yml
Labels: lgtm

#89 feat: add mdbtools
  repos.yml
Labels: lgtm

#91 feat: add nss-pem
  repos.yml
Labels: lgtm

#94 feat: add golang-github-openprinting-goipp, python-tokenize-rt
  repos.yml
Labels: approved, lgtm

#93 feat: add fonts-rocknroll
  repos.yml
Labels: approved, lgtm

#87 feat: add rust-peeking-take-while
  repos.yml
Labels: lgtm

#95 feat: add rust-thread-local, acpi, fonts-raleway
  repos.yml
Labels: lgtm

#97 feat: add toilet, larch, swtpm, nyacc, friso
  repos.yml
Labels: lgtm

#92 feat: add rust-dtoa, rust-libm, rust-rustc-version, rust-ryu, rust-semver, rust-stackvector, rust-static-assertions, rust-unreachable, rust-void
  repos.yml
Labels: lgtm

#100 feat: add rust-serde, rust-arbitrary
  repos.yml
Labels: lgtm

#101 feat: add analog,kwrited,nfacct,libnetfilter-acct,fping,termit,aha,pb…
  repos.yml
Labels: lgtm

#99 feat: add hexchat, xcvt, xserver-xorg, libss
  repos.yml
Labels: lgtm

#98 feat: add rust-compiler-builtins, rust-rustc-std-workspace-core
  repos.yml
Labels: lgtm

#106 feat: add YukariChiba to approvers
  OWNERS
Labels: approved, lgtm

#105 feat: add rust-atty
  repos.yml
Labels: approved, lgtm

#103 Add petsc
  repos.yml
Labels: approved, lgtm

#107 feat: add java-sip-api, libsis-base-java, libsis-jhdf5-java, sitemesh
  repos.yml
Labels: approved, lgtm

#108 feat: add chenchongbiao to approvers
  OWNERS
Labels: approved

#110 feat: add pysimplesoap
  repos.yml
Labels: approved, lgtm

#111 feat: add rust-smawk, rust-fnv, rust-getrandom, rust-hex, rust-seahash, rust-serde-json
  repos.yml
Labels: approved, lgtm

#113 feat: add denemo
  repos.yml
Labels: approved, lgtm

#114 feat: add libkdegames
  repos.yml
Labels: approved, lgtm

#115 feat: add lilypond
  repos.yml
Labels: approved, lgtm

#116 feat: add fonts-linex, fonts-ecolier-court, fonts-femkeklaver, fonts-mplus
  repos.yml
Labels: approved, lgtm

#112 feat: add fonts-wqy-microhei,fonts-gfs-bodoni-classic,fonts-gfs-theok…
  repos.yml
Labels: approved, lgtm

#117 feat: add fonts-beteckna, rust-humantime
  repos.yml
Labels: approved, lgtm

#118 feat: add fort-validator, libite, libuev, kconfiglib
  repos.yml
Labels: approved, lgtm

#120 feat: delete rust-humantime
  repos.yml
Labels: approved, lgtm

#121 feat: add fonts-hack
  repos.yml
Labels: approved, lgtm

#122 feat: add boolstuff
  repos.yml
Labels: approved

#124 feat: add erfs, gamgi, gliese, netdata, socket
  repos.yml
Labels: approved, lgtm

#123 feat: add paperwork,libinsane,pycountry,python-pyocr,libpillowfight
  repos.yml
Labels: approved, lgtm

#127 feat: add rust-serde-json
  repos.yml
Labels: approved, lgtm

#128 feat: add odt2txt
  repos.yml
Labels: approved, lgtm

#129 feat: add rust-regex, rust-fxhash, rust-byteorder
  repos.yml
Labels: approved, lgtm

#126 feat: add rust-syn-1, rust-derive-arbitrary, rust-smallvec
  repos.yml
Labels: approved

#130 feat: add rust-humantime, rust-device-tree
  repos.yml
Labels: approved, lgtm

#131 feat: add mate-submodules, gla11y, pluma
  repos.yml
Labels: approved, lgtm

#132 feat: add atop,meld,xdelta3,pixz,cppcheck,exif
  repos.yml
Labels: approved

#133 feat: add opensubdiv, libspnav, log4cplus, imath
  repos.yml
Labels: approved, lgtm

#134 feat: add bird, bird2, babeld, base16384, btop
  repos.yml
Labels: approved, lgtm

#138 feat: delete libspnav, log4cplus, imath
  repos.yml
Labels: approved, lgtm

#137 feat: add rust-no-panic
  repos.yml
Labels: approved, lgtm

#136 feat: add wrk,motif, xball
  repos.yml
Labels: approved, lgtm

#139 feat: add libspnav, log4cplus, imath
  repos.yml
Labels: approved, lgtm

#135 feat: add fontcustom,fonts-arundina,fonts-mlym,fonts-uralic,fonts-arphic-ukai,fonts-fork-awesome,fonts-material-design-icons-iconfont
  repos.yml
Labels: approved, lgtm

#144 feat: add ipp-usb, evilwm, python-arrow, python-exif, python-pefile
  repos.yml
Labels: approved, lgtm

#143 feat: add parser
  repos.yml
Labels: approved, lgtm

#145 feat: add debiandoc-sgml
  repos.yml
Labels: approved

#146 feat: add zutty,arping,speedtest-cli,plocate,plzip,ncftp,memtester,ar…
  repos.yml
Labels: approved

#142 feat: add rust-hashbrown and rust-once-cell
  repos.yml
Labels: approved

#140 feat: add fonts-sil-annapurna, fonts-alee, fonts-dzongkha, fonts-bpg-…
  repos.yml
Labels: approved

#148 feat: add zfs-linux
  repos.yml
Labels: approved

#147 feat: add kpcli, libsort-naturally-perl, libterm-shellui-perl, libfil…
  repos.yml
Labels: approved

#149 feat: add libnetfilter-acct
  repos.yml
Labels: approved

#150 feat: add libabigail
  repos.yml
Labels: approved

#157 feat: add python-termcolor, geographiclib, python-prov, python-geojson, python-gmpy2
  repos.yml
Labels: approved

#151 feat: add golang-github-go-macaron-toolbox
  repos.yml
Labels: approved

#152 feat: add fonts-arundina,fonts-mlym,fonts-uralic,fonts-arphic-ukai,fonts-material-design-icons-iconfont
  repos.yml
Labels: approved

#158 feat: add libgnomekbd
  repos.yml
Labels: approved

#155 feat: add rust-itoa, rust-once-cell, rust-erased-serde, rust-serde-fm…
  repos.yml
Labels: approved

#161 feat: add arping,speedtest-cli,plocate,plzip,ncftp,memtester,arp-scan
  repos.yml
Labels: approved

#159 feat: add jq, mc
  repos.yml
Labels: approved

#168 feat: add kde-dev-utils and delete xcvt, xserver-xorg-core, libss, jq
  repos.yml
Labels: approved, lgtm

#164 feat: hyfetch
  repos.yml
Labels: approved

#170 feat: fix yaml format
  repos.yml
Labels: approved

#165 Sort repos.yml
  repos.yml
Labels: approved

#171 fix: add indentation for repos.yml
  repos.yml
Labels: approved

#172 feat: Add ymllint
  .github/workflows/ymllint.yml
Labels: approved, lgtm

#174 feat: add golang-1.15 to fix snapd
  repos.yml
Labels: approved

#175 feat: add python-netaddr, python-progressbar, python-mailer, python-characteristic, python-meld3
  repos.yml
Labels: approved

#169 feat: add package imagemagick
  repos.yml
Labels: approved

#176 feat: add odc to fix magicsplusplus
  repos.yml
Labels: approved

#160 feat: add jpeginfo
  repos.yml
Labels: approved

#162 feat: add braa, fonts-cabinsketch, pgpgpg, ripit, blop, ddate, netmask, colortest
  repos.yml
Labels: approved

#178 feat: rust-walkdir
  repos.yml
Labels: approved

#180 feat: add kdeedu-data
  repos.yml
Labels: approved

#179 fix: deepin-sysdev-team is group
  repos.yml
Labels: approved

#163 feat: add weechat,libgcrypt20,gnutls28
  repos.yml
Labels: approved

#181 feat: add fonts-agave, fonts-lemonada, fonts-jura
  repos.yml
Labels: approved

#183 feat: add rdesktop
  repos.yml
Labels: approved

#153 feat: add dependencies for nexttrace
  repos.yml
Labels: approved

#184 feat: add bb, flake, missidentify
  repos.yml
Labels: approved

#187 feat: add cohomcalg,coinor-csdp,coinor-bonmin,coinor-dylp
  repos.yml
Labels: approved

#188 feat: add quart
  repos.yml
Labels: approved

#190 feat: add python-editor, python-css-parser, python-configargparse, python-iniparse, python-utmp
  repos.yml
Labels: approved

#191 feat: add bsdmainutils, exfatprogs, ntpsec, tcpdump
  repos.yml
Labels: approved

#189 feat: add libgssglue
  repos.yml
Labels: approved

#186 fix: change repo name, format yaml file
  repos.yml
Labels: approved

#194 feat: add dependencies for nexttrace
  repos.yml
Labels: approved

#195 feat: add dependencies for wlroots-git
  repos.yml
Labels: approved

#199 Revert "feat: add dependencies for nexttrace"
  repos.yml
Labels: approved

#200 Revert "fix: change repo name, format yaml file"
  repos.yml
Labels: approved

#201 fix(CI): github scripts get token error
  .github/workflows/auto-create-repo.yml
Labels: approved

#203 fix(CI): github scripts get token error
  .github/workflows/auto-create-repo.yml
Labels: approved

#196 feat: add libphp-adobd, libphp-jabber, libphp-phpmailer, libphp-snoop…
  repos.yml
Labels: approved

#198 feat: rust-tempfile
  repos.yml
Labels: approved

#206 Revert "Revert "fix: change repo name, format yaml file""
  repos.yml
Labels: approved

#207 fix: add apt update in workflow
  .github/workflows/auto-create-repo.yml
Labels: approved

#209 feat: add dependencies for pipewire
  repos.yml
Labels: approved

#210 feat: add package mtr
  repos.yml
Labels: approved

#211 Add package wireplumber
  repos.yml
Labels: approved

#192 feat: add ssh-tools,sxhkd,sm,fscrypt,empire,pngcheck,sakura
  repos.yml
Labels: approved, lgtm

#212 feat: dh-nss
  repos.yml
Labels: approved

#214 feat: add package cataclysm-dda
  repos.yml
Labels: lgtm

#213 feat: schroot
  repos.yml
Labels: approved

#216 fix: format yml file
  repos.yml
Labels: approved

#217 feat: add a new repo
  repos.yml
Labels: approved, lgtm

#219 chore: add extractpdfmark repo
  repos.yml
Labels: approved, lgtm

#220 feat: add waypipe
  repos.yml
Labels: approved

#221 chore: add libparse-debian-packages-perl repo
  repos.yml
Labels: approved

#222 chore: add ruby-minitar repo
  repos.yml
Labels: approved

#223 feat: add openvpn and strongswan
  repos.yml
Labels: approved

#224 feat: add package arch-test
  repos.yml
Labels: approved

#225 feat: aptly
  repos.yml
Labels: approved, lgtm

#227 chore: app repo
  repos.yml
Labels: approved

#229 chore: add fastfetch
  repos.yml
Labels: approved

#230 fix: revert since repo is not created
  repos.yml
Labels: approved

#232 feat: add package gopacket
  repos.yml
Labels: approved
