Repository deepin-community/Repository-Manager, pull requests merged in 2023-06, with the labels that each got.

#13 Update README.md
  README.md
Labels: approved

#17 Update repos.yml
  repos.yml
Labels: lgtm

#27 chore: add xzl01 to OWNERS
  OWNERS
Labels: approved, lgtm

#19 Update repos.yml
  repos.yml
Labels: approved, lgtm

#21 Update repos.yml
  repos.yml
Labels: approved

#28 Update repos.yml
  repos.yml
Labels: approved, lgtm

#32 add rust-menchr
  repos.yml
Labels: approved, lgtm

#29 Update repos.yml
  repos.yml
Labels: approved, lgtm

#35 update repos.yml
  repos.yml
Labels: lgtm

#39 add 'rust-unicode-xid'
  repos.yml
Labels: lgtm
