Repository deepin-community/Repository-Manager, pull requests merged in 2023-08, with the labels that each got.

#233 chore: Add sensors-applet
  repos.yml
Labels: approved

#234 feat: add kruler
  repos.yml
Labels: approved

#235 feat: add kexec-tools
  repos.yml
Labels: approved

#236 feat: add kdump
  repos.yml
Labels: approved

#228 chore: delete strongswan-nm
  repos.yml
Labels: approved

#238 feat: add 3 new packages.
  repos.yml
Labels: approved

#239 feat: Add repository exit records file
  repos-exit-records.yml
Labels: approved

#240 feat add parmap
  repos.yml
Labels: approved

#242 feat: add cpufrequtils
  repos.yml
Labels: approved

#243 feat: add ocaml-graphics
  repos.yml
Labels: approved

#244 feat: add ocaml-odoc dependencies
  repos.yml
Labels: approved

#246 feat: add bear
  repos.yml
Labels: approved

#245 feat: add iperf3
  repos.yml
Labels: approved

#247 feat: add foot
  repos.yml
Labels: approved

#250 feat: add pkgs fcft and tllist
  repos.yml
Labels: approved

#251 feat: llvm spirv
  repos.yml
Labels: approved

#249 feat: add html-xml-utils
  repos.yml
Labels: approved

#253 chore: add libopenaptx
  repos.yml
Labels: approved

#252 add gcc-11-cross
  repos.yml
Labels: lgtm

#257 feat: vte2.91
  repos.yml
Labels: approved

#258 feat: remove ldb
  repos-exit-records.yml
Labels: approved

#261 feat: add python packages (dependencies for upgrade)
  repos.yml
Labels: approved

#263 chore: add xrdp
  repos.yml
Labels: approved

#241 chore: delete ppx-tools-versioned
  repos-exit-records.yml
Labels: approved

#265 feat: add xorgxrdp
  repos.yml
Labels: approved

#262 feat: add python packages (dependencies for upgrade)
  repos.yml
Labels: approved

#237 Add dependencies for licensecheck
  repos.yml
Labels: approved, approve

#267 add usrmerge
  repos.yml
Labels: approved

#259 feat: add doctest, wf-config and wayfire
  repos.yml
Labels: approved

#268 feat: add package flit-scm
  repos.yml
Labels: approved

#269 chore: add repos
  repos.yml
Labels: approved

#271 chore: add dh-vim-addon
  repos.yml
Labels: approved

#272 feat: add wcag-contrast-ratio
  repos.yml
Labels: approved

#273 feat: add cmatrix
  repos.yml
Labels: approved

#275 feat: add wayfire-plugins-extra/wcm/wf-shell
  repos.yml
Labels: approved

#276 feat: libmoox-aliases-perl
  repos.yml
Labels: approved

#277 feat: debugpy
  repos.yml
Labels: approved

#278 feat: sphinx-inline-tabs
  repos.yml
Labels: approved

#279 chore: update repos
  repos.yml
Labels: approved

#280 Add libraries
  repos.yml
Labels: approved

#281 chore: add cups-backend-bjnp
  repos.yml
Labels: approved

#285 chore: add kodi dependencies
  repos.yml
Labels: approved

#282 feat: add rocm-smi-lib
  repos.yml
Labels: approved

#284 feat: libmouse-perl
  repos.yml
Labels: approved

#286 feat: dot2tex
  repos.yml
Labels: approved

#288 feat: add dependencies for cataclysm-dda
  repos.yml
Labels: approved

#289 feat: add vfit
  repos.yml
Labels: approved

#287 chore: update repos
  repos.yml
Labels: approved

#290 feat: add fonts-pc
  repos.yml
Labels: approved

#293 feat: add libnvme
  repos.yml
Labels: approved

#294 feat: add fonts-atarismall
  repos.yml
Labels: approved

#296 chroe: add deps
  repos.yml
Labels: approved

#297 chore: add dependencies
  repos.yml
Labels: approved

#299 chore: delete libgssglue
  repos.yml
Labels: approved

#300 chore: add libgssglue
  repos.yml
Labels: approved

#301 chore: add ruby-mini-portile2
  repos.yml
Labels: approved

#295 feat: add architecture-properties
  repos.yml
Labels: approved

#298 feat: add openttd
  repos.yml
Labels: approved

#302 feat: add boost 1.81
  repos.yml
Labels: approved

#292 feat: add minetest
  repos.yml
Labels: approved

#303 feat: add denepdencies for openttd
  repos.yml
Labels: approved

#305 feat: add dependencies for prismlauncher
  repos.yml
Labels: approved

#306 feat: add libmypaint
  repos.yml
Labels: approved

#307 feat: add catcodec
  repos.yml
Labels: approved

#304 feat: add nml
  repos.yml
Labels: approved
