Repository deepin-community/Repository-Manager, pull requests merged in 2024-11, with the labels that each got.

#924 feat: Add sphinx-sitemap
  repos.yml
Labels: needs-ok-to-test

#925 chore: Rm pkg-config package
  repos-exit-records.yml
Labels: approved, ok-to-test

#928 feat: add node-puka node-pako node-istextorbinary
  repos.yml
Labels: approved

#930 add podman (previously libpod)
  repos.yml
Labels: approved

#932 add golang-github-buger-goterm golang-github-containers-gvisor-tap-vsocks golang-github-containers-psgo golang-github-coreos-stream-metadata-go golang-github-crc-org-crc golang-github-digitalocean-go-libvirt golang-github-digitalocean-go-qemu golang-github-docker-go-plugins-helpers golang-github-dtylman-scp golang-github-gorilla-schema golang-github-mdlayher-vsock golang-github-pkg-profile
  repos.yml
Labels: approved

#934 add golang-github-alecaivazis-survey golang-github-apparentlymart-go-cidr golang-github-areyoulazy-libhosty golang-github-elazarl-goproxy golang-github-inetaf-tcpproxy golang-github-linuxkit-virtsock golang-github-openshift-api golang-github-pbnjay-memory golang-gopkg-h2non-filetype.v1 golang-gvisor-gvisor golang-github-pborman-uuid
  repos.yml
Labels: approved

#935 add golang-github-armon-go-proxyproto golang-github-google-subcommands golang-github-hinshun-vt10x golang-github-kballard-go-shellquote golang-pty golang-github-mgutz-ansi golang-github-netflix-go-expect golang-github-paulrosania-go-charset
  repos.yml
Labels: approved

#936 Remove duplicate info line
  repos.yml
Labels: approved

#933 chore: add libqalculate
  repos.yml
Labels: approved, ok-to-test

#938 Sort & add conmon
  repos.yml
Labels: approved

#939 add xcb-util-errors
  repos.yml
Labels: approved

#940 add libencode-eucjpascii-perl
  repos.yml
Labels: approved

#941 add kf6 pkg list
  repos.yml
Labels: approved

#942 add mkosi
  repos.yml
Labels: approved

#943 add incus and deps
  repos.yml
Labels: approved

#945 add deps for incus
  repos.yml
Labels: approved

#946 add deps for incus
  repos.yml
Labels: approved

#948 add kf6 deps
  repos.yml
Labels: needs-ok-to-test

#952 add kglobalacceld
  repos.yml
Labels: needs-ok-to-test

#953 add kdecoration about qt6
  repos.yml
Labels: needs-ok-to-test

#954 Sort repos.yml and add cproto and mpfi
  repos.yml
Labels: approved

#955 add cpanminus and deps
  repos.yml
Labels: approved

#956 add rpki-trust-anchors
  repos.yml
Labels: approved

#845 feat: remove useless python package
  repos-exit-records.yml
Labels: approved

#959 chore: add pcp
  repos.yml
Labels: approved

#958 update milou and kwayland
  repos.yml
Labels: needs-ok-to-test
