Repository deepin-community/Repository-Manager, pull requests merged in 2024-12, with the labels that each got.

#965 chore: add llvm-19 and spriv-19
  repos.yml
Labels: approved

#966 Add gnome-control-center & gnome-settings-daemon
  repos.yml
Labels: approved, needs-ok-to-test

#968 add passt
  repos.yml
Labels: approved

#972 add python-autocommand python-inflect jaraco.context
  repos.yml
Labels: approved

#971 Add tecla
  repos.yml
Labels: needs-ok-to-test

#974 feat: add mvdsv
  repos.yml
Labels: needs-ok-to-test

#975 add libspf2
  repos.yml
Labels: approved

#976 chore: add deskflow and txt2tag
  repos.yml
Labels: approved

#977 add emacs-addons-metapackages
  repos.yml
Labels: approved

#978 add cups-pk-helper gnome-backgrounds gnome-themes-extra
  repos.yml
Labels: approved, needs-ok-to-test

#979 Add gnome-bluetooth3
  repos.yml
Labels: approved, needs-ok-to-test

#980 chore: add tuned
  repos.yml
Labels: approved

#981 master
  repos.yml
Labels: approved

#982 chore: add supervisor
  repos.yml
Labels: approved

#983 chore: add dump-init
  repos.yml
Labels: approved

#984 add topic-emacs
  repos.yml
Labels: approved, needs-ok-to-test

#985 add libpod-readme-perl etc.
  repos.yml
Labels: approved, needs-ok-to-test
