Repository deepin-community/Repository-Manager, pull requests merged in 2024-10, with the labels that each got.

#879 chore: add containers OCI stage1
  repos.yml
Labels: approved

#880 add libubootenv
  repos.yml
Labels: approved

#881 chore: add scheme-bytestructures
  repos.yml
Labels: approved, needs-ok-to-test

#882 topic oci
  repos.yml
Labels: approved

#878 feat: add python3-absl
  repos.yml
Labels: approved, ok-to-test

#883 add golang-github-rs-xid
  repos.yml
Labels: approved

#884 add golang-github-antlr-antlr4 golang-github-stoewer-go-strcase
  repos.yml
Labels: approved

#888 add golang-github-go-openapi-jsonpointer golang-github-invopop-yaml golang-github-mailru-easyjson golang-github-mohae-deepcopy golang-github-perimeterx-marshmallow
  repos.yml
Labels: approved

#889 add golang-github-go-test-deep golang-github-josharian-intern golang-github-ugorji-go-codec
  repos.yml
Labels: approved

#891 add go-containerregistry golang-github-azure-azure-sdk-for-go golang-github-cloudflare-backoff golang-github-coreos-go-oidc golang-github-coreos-go-oidc-v3 golang-github-go-jose-go-jose.v3 golang-github-go-openapi-errors golang-github-go-openapi-runtime golang-github-go-openapi-strfmt golang-github-go-openapi-validate golang-github-gregjones-httpcache golang-github-hashicorp-golang-lru-v2 golang-github-jedisct1-go-minisign golang-github-jellydator-ttlcache golang-github-kubernetes-cri-api golang-github-peterbourgon-diskv golang-github-pkg-browser golang-github-rs-cors golang-github-sebdah-goldie golang-github-segmentio-ksuid golang-github-shibumi-go-pathspec golang-github-sigstore-protobuf-specs golang-github-spiffe-go-spiffe golang-github-thalesignite-crypto11 golang-github-theupdateframework-go-tuf golang-github-transparency-dev-merkle golang-github-urfave-cli-v2 golang-github-veraison-go-cose golang-github-zmap-zlint golang-k8s-sigs-release-utils golang-webpki-org-jsoncanonicalizer relic trillian
  repos.yml
Labels: approved

#892 add golang-github-gin-contrib-sse
  repos.yml
Labels: approved

#894 add golang-github-zmap-zcrypto
  repos.yml
Labels: approved

#893 chore(repos.yml): add rnp
  repos.yml
Labels: approved

#895 add golang-github-op-go-logging golang-github-weppos-publicsuffix-go golang-github-zmap-rc2
  repos.yml
Labels: approved

#898 add golang-github-howeyc-gopass golang-github-go-openapi-loads golang-gomemcache golang-github-thales-e-security-pool golang-github-dnaeon-go-vcr golang-github-google-go-github golang-github-golang-leveldb golang-github-x448-float16
  repos.yml
Labels: approved

#899 add golang-github-google-go-cmp golang-mongodb-mongo-driver
  repos.yml
Labels: approved

#900 add golang-github-gofrs-uuid golang-github-montanaflynn-stats golang-github-pquerna-cachecontrol golang-goleveldb golang-github-zalando-go-keyring
  repos.yml
Labels: approved

#901 add golang-github-xdg-go-scram golang-sslmate-src-go-pkcs12
  repos.yml
Labels: approved

#902 add golang-github-xdg-go-pbkdf2
  repos.yml
Labels: approved

#903 add golang-github-xdg-go-stringprep golang-github-shopspring-decimal
  repos.yml
Labels: approved

#904 add golang-gopkg-natefinch-lumberjack.v2
  repos.yml
Labels: approved

#905 add golang-github-oklog-run
  repos.yml
Labels: approved

#907 add golang-bitbucket-creachadair-shell golang-github-fortytw2-leaktest golang-github-eapache-go-resiliency
  repos.yml
Labels: approved

#908 add golang-github-go-openapi-spec golang-github-cockroachdb-cockroach-go
  repos.yml
Labels: approved

#909 add tftp-hpa
  repos.yml
Labels: approved

#912 dep of brz: configobj patiencediff python-fastbencode python-launchpadlib python-merge3 python-setuptools-gettext
  repos.yml
Labels: approved

#913 dep of brz: python-wadllib lazr.uri
  repos.yml
Labels: approved
