Repository deepin-community/Repository-Manager, pull requests merged in 2024-08, with the labels that each got.

#816 chore: add openjdk(18-21)
  repos.yml
Labels: approved

#819 add xtensor
  repos.yml
Labels: approved

#818 chore: remove useless openjdk-(18,19,20) add openjdk-8
  repos.yml
Labels: approved

#821 Sort repos.yml & add python-openai
  repos.yml
Labels: approved

#823 chore: add misans and read-edid
  repos.yml
Labels: approved

#824 chore: add log4cpp
  repos.yml
Labels: approved

#828 add fonts-adobe-source-han-cjk
  repos.yml
Labels: approved

#831 feat: add zig language
  repos.yml
Labels: needs-ok-to-test

#833 feat: add greenboot & nss-altfiles
  repos.yml
Labels: approved, needs-ok-to-test

#841 chore: add libmodule-manifest-perl
  repos.yml
Labels: approved

#842 add dmg2img
  repos.yml
Labels: approved
