Repository deepin-community/Repository-Manager, pull requests merged in 2024-09, with the labels that each got.

#844 add microcode
  repos.yml
Labels: approved

#847 chore： yaml lint
  repos.yml
Labels: approved

#848 chore: add blender
  repos.yml
Labels: approved

#852 chore: add uresourced
  repos.yml
Labels: approved

#853 chore: add ptex-base
  repos.yml
Labels: approved

#854 chore: add ncbi-blast+
  repos.yml
Labels: approved

#856 add fcitx5-unikey
  repos.yml
Labels: approved

#858 mdevctl
  repos.yml
Labels: approved

#859 add hw-probe
  repos.yml
Labels: approved

#860 chore: add ddccontroal and checksec
  repos.yml
Labels: approved

#861 chore: add ddccontrol-db
  repos.yml
Labels: approved

#862 chore: add libfile-next-perl
  repos.yml
Labels: approved, needs-ok-to-test

#865 Add Mozc input method
  repos.yml
Labels: approved

#866 chore: add python-blessed python-curtsies python-cwcwidth
  repos.yml
Labels: needs-ok-to-test

#870 add python-pytest-retry
  repos.yml
Labels: approved

#872 add emscripten and deps
  repos.yml
Labels: approved

#873 chore: add some R package
  repos.yml
Labels: approved

#877 add pangomm2.48 and cpdb-libs
  repos.yml
Labels: approved, needs-ok-to-test
