Repository deepin-community/Repository-Manager, pull requests merged in 2025-02, with the labels that each got.

#999 add bootstrap-html node-fortawesome-fontawesome-free node-html-webpac…
  repos.yml
Labels: approved

#1001 chore: add planner libgda5
  repos.yml
Labels: needs-ok-to-test

#998 chore: Remove osc tools
  .github/workflows/auto-create-repo.yml
Labels: approved

#1009 chore: add libsdl3 libsdl3-image libsdl3-mixer libsdl3-ttf
  repos.yml
Labels: needs-ok-to-test

#1011 add libgedit-gfls
  repos.yml
Labels: approved

#1010 chore: add kicad kicad-footprints kicad-packages3d kicad-symbols kicad-templates ngspice opencascade
  repos.yml
Labels: approved, needs-ok-to-test

#1012 add antlr4-cpp-runtime eclipse-equinox eclipse-platform fwupd-efi li…
  repos.yml
Labels: approved

#1014 add node-change-case
  repos.yml
Labels: approved

#1016 Add libjodycode
  repos.yml
Labels: approved

#1017 chore: add binutils-riscv64-unknown-elf gcc-riscv64-unknown-elf
  repos.yml
Labels: needs-ok-to-test

#1018 add depends: python3-iniparse、crudini
  repos.yml
Labels: approved, needs-ok-to-test

#1019 feat： add nodejs deps
  repos.yml
Labels: approved

#1021 chore: add libstdc++ deps
  repos.yml
Labels: approved, needs-ok-to-test
