Repository deepin-community/Repository-Manager, pull requests merged in 2025-03, with the labels that each got.

#1023 add sphinxcontrib-mermaid python-autodocsumm pytest-cython
  repos.yml
Labels: approved

#1025 chore: add llvm-20
  repos.yml
Labels: approved

#1026 chore: add zig0.14
  repos.yml
Labels: approved

#1024 chore: add scilab deps
  repos.yml
Labels: approved, needs-ok-to-test

#1027 chore: add lucene8 deps
  repos.yml
Labels: needs-ok-to-test

#1028 chore: add janest-base ocaml-intrinsics-kernel ppx-here ppx-let
  repos.yml
Labels: needs-ok-to-test

#1029 add wtmpdb
  repos.yml
Labels: approved

#1039 chore: add qoi
  repos.yml
Labels: needs-ok-to-test

#1038 feat: add rsetup
  repos.yml
Labels: approved

#1040 feat: add librtui
  repos.yml
Labels: approved

#1041 chore: add picocom
  repos.yml
Labels: approved

#1042 feat: add waydroid
  repos.yml
Labels: approved

#1033 chore: add pyocd pyusb
  repos.yml
Labels: needs-ok-to-test
